[package]
name = "cov-mark"
version = "1.0.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "Manual coverage marks."
repository = "https://github.com/matklad/cov-mark"
documentation = "https://docs.rs/cov-mark"

keywords = ["coverage", "test"]
categories = ["development-tools"]
